name: Checkout

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  workflow_dispatch:

env:
  artifact: workflow-tests-checkout

jobs:
  checkout:
    name: Checkout

    runs-on: ubuntu-latest

    outputs:
      artifact: ${{ env.artifact }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.artifact }}
          path: .

  build-and-test:
    name: Build and test
    needs: [checkout]
    uses: ./.github/workflows/build-and-test.yaml
    with:
      artifact: ${{ needs.build.outputs.artifact }}